#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" <<-EOSQL
    CREATE USER $POSTGRES_NONROOT_USER with encrypted password '$POSTGRES_NONROOT_PASSWORD';
    CREATE DATABASE $WEDDING_DB;
    GRANT ALL PRIVILEGES ON DATABASE "$WEDDING_DB" TO "$POSTGRES_NONROOT_USER";
    ALTER USER "$POSTGRES_NONROOT_USER" CREATEDB;
EOSQL