# Generated by Django 4.0.1 on 2022-02-16 10:55

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
                'default_manager_name': 'default_manager',
            },
            managers=[
                ('default_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('first_name', models.TextField(help_text='First Name')),
                ('last_name', models.TextField(help_text='Last Name')),
                ('is_attending', models.BooleanField(default=True, null=True)),
                ('meal', models.CharField(blank=True, choices=[('beef', 'Meat balls'), ('fish', 'Char (Saibling, Fish)'), ('vegetarian', 'Vegetarian dumpling tris'), ('child', "Children's menu: Schnitzel")], max_length=46, null=True)),
                ('is_child', models.BooleanField(default=False)),
                ('comments', models.TextField(blank=True, help_text='Anything else we should know about?')),
                ('registration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wedding.registration')),
            ],
            options={
                'abstract': False,
                'default_manager_name': 'default_manager',
            },
            managers=[
                ('default_manager', django.db.models.manager.Manager()),
            ],
        ),
    ]
